= Nerva-rowwise Python manual
:copyright: Copyright 2024 Wieger Wesselink
:author: Wieger Wesselink
:email: j.w.wesselink@tue.nl
:doctype: book
:toc: left
:toc2:
:toc-title: pass:[<h3>Contents</h3>]
:css-signature: demo
:stem: latexmath
:icons: font
:description: Documentation for the nerva-rowwise repository.
:imagesdir: images
:bibliography: nerva.bib
:library: nerva-rowwise
:mlptool: mlp.py

Wieger Wesselink <j.w.wesselink@tue.nl>
ifdef::env-github[]
:note-caption: :information_source:
endif::[]

++++
<style>
  .small-code .content pre {
      font-size: 0.7em;
  }
</style>
++++

== Introduction
This document describes the Python bindings of the {library} library.

== Installation
The {library} Python bindings can be installed via `pip`. The installation is done via a https://github.com/wiegerw/nerva-rowwise/blob/main/python/setup.py[setup.py] script. The script has several dependencies, that need to be resolved using environment variables.

=== Dependencies
- Intel MKL library https://www.intel.com/content/www/us/en/developer/tools/oneapi/onemkl.html[oneMKL]
- FMT https://github.com/fmtlib/fmt
- Eigen https://eigen.tuxfamily.org/
- pybind11 https://github.com/pybind/pybind11

The MKL dependency can be resolved by setting the `MKL_ROOT` environment variable, or by setting the `ONEAPI_ROOT` environment variable.

To resolve the FMT, Eigen and pybind11 dependencies, the environment variables
`EIGEN_INCLUDE_DIR`, `FMT_INCLUDE_DIR` and `PYBIND11_INCLUDE_DIR` can be set.

An alternative solution is to use CMake to resolve these three dependencies, see also the
link:nerva-cpp.adoc#cmake-build[CMake install] section in the C++ documentation. The `cmake` command causes the three libraries to be downloaded automatically in the `_deps` subdirectory of the CMake build directory. After that it is sufficient to set the environment variable `CMAKE_DEPS_DIR`.

The `nerva` Python module can then be installed using
[source]
----
cd python
pip install .
----

== Command line tools
The tool `mlp.py` can be used to do training experiments with multilayer perceptrons.

=== The tool mlp.py
An example invocation of the `mlp.py` tool is

[source]
----
include::../examples/cifar10_sparse_python.sh[tag=doc]
----
This will train a CIFAR-10 model using an MLP consisting of three layers with activation functions ReLU, ReLU and no activation. Note that it automatically downloads the CIFAR-10 dataset in the folder `../data` if it doesn't yet exist.

The output may look like this:
[.small-code]
[source]
----
=== Nerva python model ===
Sequential(
  Sparse(output_size=1024, density=0.042382812500000006, activation=ReLU(), optimizer=Nesterov(0.9), weight_initializer=Xavier),
  Sparse(output_size=1024, density=0.06357421875000001, activation=ReLU(), optimizer=Nesterov(0.9), weight_initializer=Xavier),
  Dense(output_size=10, activation=NoActivation(), optimizer=Nesterov(0.9), weight_initializer=Xavier, dropout=0.0)
)
loss = SoftmaxCrossEntropyLoss()
scheduler = ConstantScheduler(lr=0.009999999776482582)
layer densities: 133325/3145728 (4.238%), 66662/1048576 (6.357%), 10240/10240 (100%)


=== Training Nerva model ===
epoch   0  lr: 0.01000000  loss: 2.30246344  train accuracy: 0.10724000  test accuracy: 0.11390000  time: 0.00000000s
epoch   1  lr: 0.01000000  loss: 1.89570341  train accuracy: 0.32142000  test accuracy: 0.32030000  time: 4.15395873s
epoch   2  lr: 0.01000000  loss: 1.66956488  train accuracy: 0.40332000  test accuracy: 0.40220000  time: 3.60670412s
epoch   3  lr: 0.01000000  loss: 1.53549386  train accuracy: 0.45616000  test accuracy: 0.44940000  time: 3.24853144s
epoch   4  lr: 0.01000000  loss: 1.43913857  train accuracy: 0.49054000  test accuracy: 0.47920000  time: 3.29059404s
epoch   5  lr: 0.01000000  loss: 1.36875251  train accuracy: 0.51380000  test accuracy: 0.49070000  time: 3.83244992s
epoch   6  lr: 0.01000000  loss: 1.29761993  train accuracy: 0.54106000  test accuracy: 0.50710000  time: 3.59350869s
epoch   7  lr: 0.01000000  loss: 1.23931273  train accuracy: 0.56170000  test accuracy: 0.51690000  time: 3.96624650s
----

include::nerva-cpp.adoc[tags=mlptool-options]

include::nerva-cpp.adoc[tags=general-options]

include::nerva-cpp.adoc[tags=random-generator-options]

include::nerva-cpp.adoc[tags=layer-configuration-options]

include::nerva-cpp.adoc[tags=training-configuration-options]

include::nerva-cpp.adoc[tags=pruning-options]

include::nerva-cpp.adoc[tags=computation-options]

include::nerva-cpp.adoc[tags=dataset-options]

===== Miscellaneous options
* `--precision <value>`
The precision used for printing matrices.
* `--info`
Print detailed information about the multilayer perceptron.
* `--timer`
Print timer messages.

include::nerva-cpp.adoc[tags=io]
