include::settings.adoc[]

include::../include/matrix-operations.adoc[]

Using this table leads to concise and uniform code. For example, the backpropagation implementation of a softmax layer looks like this:
[.small-code]
[source,cpp]
----
include::../../../include/nerva/neural_networks/layers.h[tag=matrix_operations]
----
See the specification document https://wiegerw.github.io/nerva-rowwise/pdf/nerva-library-specifications.pdf[Nerva library specifications] for an overview of how these matrix operations are used.

=== Eigen library
The {library} uses the https://eigen.tuxfamily.org/[Eigen library] for representing matrices. The matrix operations in table <<table_matrix_operations>> have been implemented using Eigen, see the file https://github.com/wiegerw/nerva-rowwise/blob/main/include/nerva/neural_networks/matrix_operations.h[matrix_operations.h].

=== MKL library
Using the Eigen library alone is not sufficient for obtaining high performance. Therefore, the {library} uses the https://en.wikipedia.org/wiki/Math_Kernel_Library[Intel Math Kernel library (MKL)] as a backend. The Eigen library supports MKL by means of the compiler flag `EIGEN_USE_MKL_ALL`, see also https://eigen.tuxfamily.org/dox/TopicUsingIntelMKL.html[TopicUsingIntelMKL.html].
Note that the MKL library is included in the https://www.intel.com/content/www/us/en/developer/tools/oneapi/base-toolkit-download.html[Intel oneAPI base toolkit].

The MKL library supports a number of highly efficient, but extremely low-level interfaces for matrix operations. See https://www.intel.com/content/www/us/en/docs/onemkl/developer-reference-c/2024-2/blas-and-sparse-blas-routines.html[blas-and-sparse-blas-routines.html] for an overview. The {library} contains matrix classes that hide those low-level details from the user. The table below gives an overview of them.

|===
|Header file |Description

|`link:https://github.com/wiegerw/nerva-rowwise/blob/main/include/nerva/neural_networks/mkl_dense_vector.h[mkl_dense_vector.h]`
|A class `dense_vector_view` that wraps a raw pointer to a vector.

|`link:https://github.com/wiegerw/nerva-rowwise/blob/main/include/nerva/neural_networks/mkl_dense_matrix.h[mkl_dense_matrix.h]`
|A class `dense_matrix_view` that wraps a raw pointer to a matrix, and a class
`dense_matrix` that stores a dense matrix.

|`link:https://github.com/wiegerw/nerva-rowwise/blob/main/include/nerva/neural_networks/mkl_sparse_matrix.h[mkl_sparse_matrix.h]`
|A class `sparse_matrix_csr` footnote:[Note that the name `sparse_matrix` could not be used due to a conflict with a #define of the same name buried deep inside the MKL library code] that stores a sparse matrix in
https://en.wikipedia.org/wiki/Sparse_matrix#Compressed_sparse_row_(CSR,_CRS_or_Yale_format)[compressed sparse row] (CSR) format.
|===

TIP: In C++23 the implementation of sparse matrices in CSR format can be greatly simplified, as shown by https://github.com/BenBrock/matrix-cpos[Ben Brock].

NOTE: The sparse CSR matrix functions in the MKL library take an argument of the opaque type `sparse_matrix_t`. It stores unspecified properties of a sparse matrix. This parameter is poorly documented, and it is unknown when this parameter should be recalculated. For safety reasons, the {library} recalculates this parameter after every change to a sparse matrix, which may cause some inefficiencies. See also the function `sparse_matrix_csr::construct_csr` and
https://www.intel.com/content/www/us/en/docs/onemkl/developer-reference-c/2024-1/mkl-sparse-create-csr.html[mkl_sparse_?_create_csr].
