include::settings.adoc[]

include::../include/performance.adoc[]

=== Nerva computation mode
In general, the performance of Eigen is very good. But occasionally, the generated code for a matrix expression can be quite poor. Especially in case of backpropagation calculations this can have a huge impact on the performance. The {library} uses a global setting `NervaComputation` to experiment with other implementations. For example, the function `softmax_layer::feedforward` contains this:
[.small-code]
[source,cpp]
----
include::../../../include/nerva/neural_networks/layers.h[tag=nerva_computation]
----
In this case, the default version `computation::eigen` turned out to have very poor performance. A direct call to an MKL routine is used to solve this problem. The `NervaComputation` setting is also used to experiment with BLAS implementations and SYCL implementations. See the file https://github.com/wiegerw/nerva-rowwise/blob/main/include/nerva/neural_networks/optimizers.h[optimizers.h] for some examples of that.

TIP: The command line tool `mlp` has an option `--computation` to set the computation mode.

