name: Deploy LaTeX documentation

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache TeX Live
        uses: actions/cache@v3
        with:
          path: /usr/local/texlive
          key: ${{ runner.os }}-texlive-${{ hashFiles('**/texlive-version.txt') }}  # Use a version file to create a unique key
          restore-keys: |
            ${{ runner.os }}-texlive-

      - name: Set up TeX Live
        run: |
          if [ ! -d "/usr/local/texlive" ]; then
            echo "Installing TeX Live..."
            sudo apt-get update
            sudo apt-get install -y wget
            wget -qO- http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz | tar xz
            cd install-tl-*
            echo "selected_scheme scheme-full" > texlive.profile
            echo "TEXLIVE_INSTALL_PREFIX=/usr/local/texlive" >> texlive.profile
            echo "TEXLIVE_VERSION=2023" >> texlive.profile  # Specify the version you want
            echo "selected_scheme scheme-full" >> texlive.profile
            echo "option_install_default_packages 0" >> texlive.profile  # Prevent default packages from being installed
            echo "option_install_packages texlive,texlive-latex-extra,texlive-fonts-recommended,texlive-xetex,texlive-science" >> texlive.profile
            ./install-tl --profile=texlive.profile
          else
            echo "TeX Live is already installed."
          fi

      - name: Compile LaTeX
        run: |
          mkdir -p output_directory
          cd doc
          pdflatex nerva-library-specifications.tex
          bibtex nerva-library-specifications
          pdflatex nerva-library-specifications.tex
          pdflatex nerva-library-specifications.tex
          cp nerva-library-specifications.pdf ../output_directory

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output_directory
          destination_dir: pdf

