name: Deploy AsciiDoc to GitHub Pages

on:
  push:
    branches:
      - main  # Or your default branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'  # Specify your Ruby version

      - name: Install Asciidoctor
        run: gem install asciidoctor

      - name: Create output directory
        run: mkdir -p output_directory

      - name: Convert AsciiDoc to HTML
        run: asciidoctor -D ./output_directory ./doc/nerva-c++.adoc

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output_directory
          force_orphan: true
