name: Deploy LaTeX documentation

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up TeX Live
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive texlive-latex-extra texlive-fonts-recommended texlive-xetex texlive-science

      - name: Compile LaTeX
        run: |
          mkdir -p pdf_directory
          cd doc
          pdflatex nerva-libraries-implementation.tex
          bibtex nerva-libraries-implementation
          pdflatex nerva-libraries-implementation.tex
          pdflatex nerva-libraries-implementation.tex
          cp nerva-libraries-implementation.pdf ../pdf_directory

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./pdf_directory
